### ISSUE TITLE
Publish as an npm module?

### ISSUE THREAD

**Issue by aarohmankad** [mxstbr/micro-open-graph#20]
Hey folks,

Found this repo searching for an easy way to create rich link previews. I was wondering if you've considered publishing the package as an npm module as well? Mainly for projects that maybe don't lend themselves to a microservice architecture, or don't prefer it.

If you need someone to take lead on it, I'd be happy to look into it :slightly_smiling_face:

**Comment by mxstbr** [comment]
Might as well just use `metascraper` directly, no need to publish this to npm, it doesn't do anything else apart from starting a server!

See the code here: https://github.com/withspectrum/micro-open-graph/blob/master/index.js
