### ISSUE TITLE
Metascraper vs OpenGraphScraper

### ISSUE THREAD

**Issue by oyeanuj** [mxstbr/micro-open-graph#3]
Hey Max, thanks as always for putting out the work! I was wondering if you had come across https://github.com/ianstormtaylor/metascraper.

It seems to do what open-graph-scraper does but with higher accuracy. 

Thoughts?

**Comment by oyeanuj** [comment]
Another one that I had played around with, which has a lot more information, like product information, etc and is node-based is https://github.com/blakeembrey/node-scrappy

**Comment by mxstbr** [comment]
Sounds good to me, more accurate is always a win. I trust @ianstormtaylor to do good work, so a PR switching to metascraper would be appreciated! (it's also using Promises, which work 🔥 with `micro` and won't require us to lock the Node version to 6.x as we currently)

**Comment by mxstbr** [comment]
Didn't want to wait anymore for that quality, so shipped it in 7655ac0!
